version: '3.7'

services:

  examenes_escritos:
    env_file:
      - settings.env
    environment:
      PATH_PREFIX: titupr
    build: ./contenedorEscritos
    restart: always
    container_name: examenes_escritos
    volumes:
      - ./contenedorEscritos/examenesEscritos:/code
    depends_on:
      - bd_examen_escrito
       
      
  bd_examen_escrito:
    image: mariadb
    restart: always
    env_file:
      - bd.env
    volumes:
      - ./contenedorEscritos/dataBD:/var/lib/mysql


  nginx_examen_escrito:
    image: nginx
    restart: always
    volumes:
      - ./contenedorEscritos/nginx/templates:/etc/nginx/templates
      - ./contenedorEscritos/examenesEscritos/static:/static
    depends_on:
      - examenes_escritos
    ports:
      - 8000:80
    environment:
      PATH_PREFIX: titupr
